---
title: "再次出海"
---

就叫我以實瑪利吧。

幾年前，我口袋裡沒幾個錢，岸上也沒什麼事能引起我的興趣，於是我想，不如出海航行一番，去看看大海。事實上，每當我發現自己嘴角下垂、神情陰鬱，偶而會在棺材鋪前駐足，或是遇上葬禮便不自覺地跟著隊伍走時，我就知道，是時候該儘快回到海上了。這種感受並不特別，畢竟所有人對海洋都有類似的嚮往。

就像羅盤的磁針總被磁力吸引，所有人——無論男女老少——遲早都會受到海洋的召喚。內陸的人們也一樣，無論來自小巷、大街，或東西南北何方，終究會屈服於河流、池塘、湖泊與海洋的呼喚。古波斯人為何崇拜海洋？這一切絕非毫無意義。我只知道，我內心焦灼，渴望再度揚帆遠航，去見識那些遙遠而陌生的事物。

不過，我可不是以乘客的身分出海的。畢竟，當乘客得有錢包，而空的錢包只不過是塊破布。再說，乘客通常會暈船、夜裡睡不好，也享受不到多少樂趣。我從不以乘客身分出海，也不當船長或廚師。

不，我出海時，是以普通水手的身分去的。沒錯，他們會對我呼來喝去，讓我像五月草地上的蚱蜢一樣跳來跳去。要是某個老船長命令我拿掃帚去甲板打掃呢？好吧，無論那些老船長怎麼使喚我，無論他們如何對我拳打腳踢，我心裡都明白這再正常不過——畢竟每個人，或多或少，都得經歷同樣的待遇。

再者，我之所以總是以水手身分出海，是因為他們會付我工錢，而我可從沒聽說過乘客能拿到半毛錢。恰恰相反，乘客還得自己掏腰包呢。最後，我選擇當水手，是為了享受船艙頂層的新鮮空氣和有益健康的運動。

當過商船水手後，我現在決定去捕鯨。我想加入捕鯨航行的主要原因，正是那頭巨大的鯨魚本身。如此龐大而神秘的怪物激起了我的好奇心。此外，鯨魚出沒的那片狂野而遙遠的海域，也讓我渴望踏上捕鯨之旅。

我往舊行李袋裡塞了一兩件襯衫，夾在腋下便出發了，最終在十二月的某個星期六晚上抵達新貝德福德。然而，當我得知前往楠塔基特的小船已經啟航，且下週一之前都沒有其他方式能抵達該地時，我感到十分失望。

現在，我必須在新貝德福德度過一個夜晚、一個白天，再加一個夜晚，因此得先找個地方吃飯睡覺。那晚寒冷刺骨，陰鬱沉沉，我在這地方舉目無親，身上的錢也所剩無幾。在查探了幾處之後，我終於來到一家名為「噴水鯨客棧——彼得．科芬」的店，決定進去瞧瞧。一進門，我就看見一群年輕水手圍坐在桌邊。於是我叫來老闆，告訴他我想租間房，但他說客棧已經客滿，每張床都有人了。

「不過，」他說道，「您應該不介意和一位魚叉手同睡一張床吧？我猜您要是去——」。

